app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/imdb_hu
      password: '1234'
      pool-size: 30
      username: norab

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  flyway:
    enabled: true
