app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/imdb_hu
      password: '1234'
      pool-size: 30
      username: norab

    users:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/users
      password: '1234'
      pool-size: 30
      username: norab

server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/data
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: true
    serialization:
      INDENT_OUTPUT: true
